### ISSUE TITLE
Speech to text for dutch not working

### ISSUE THREAD

**Issue by Coolykoen** [tonym128/shhh-bot#12]
Thanks again for listening to my suggestions on reddit.

Im am trying to make it speech to text from dutch voice notes. however, here you can see that it simply tries to interpret it as english:

![image](https://github.com/tonym128/shhh-bot/assets/48558949/86a77c7e-256a-4ec0-8e0f-2ffa163af4a1)
Its not making sense because i was speaking dutch haha.
This was with the large v3 model, but before your updates, it did the exact same thing without the model env. so i suppose that was with base?

Current compose:
```
version: "3"
services:
  shhhbot:
    container_name: shhhbot
    hostname: shhhbot
    restart: always
    image: ghcr.io/tonym128/shhh-bot
    environment:
      - model=large-v3-q5_0
      - SHHH_API_KEY=API_KEY
```

**Comment by cchrkk** [comment]
Same with italian, what's weird is that I sent 2 voice messages spoken in italian:

-The first came out like this:
 (speaking in foreign language)
 (speaking in foreign language)
 (speaking in foreign language)
 
-The second one came translated perfectly to italian 😂
 
 
 I think that whisper.cpp needs the auto language detection, because it defaults to ENG
 
 
![image](https://github.com/tonym128/shhh-bot/assets/12370126/1cf6d9ff-9f2c-4538-a267-3cbc3d5fc2e2)
EDIT: Ok It's probably not that easy

**Comment by tonym128** [comment]
> Thanks again for listening to my suggestions on reddit.
> 
> Im am trying to make it speech to text from dutch voice notes. however, here you can see that it simply tries to interpret it as english:
> 
> ![image](https://github.com/tonym128/shhh-bot/assets/48558949/86a77c7e-256a-4ec0-8e0f-2ffa163af4a1)
> Its not making sense because i was speaking dutch haha.
> This was with the large v3 model, but before your updates, it did the exact same thing without the model env. so i suppose that was with base?
> 
> Current compose:
> ```
> version: "3"
> services:
>   shhhbot:
>     container_name: shhhbot
>     hostname: shhhbot
>     restart: always
>     image: ghcr.io/tonym128/shhh-bot
>     environment:
>       - model=large-v3-q5_0
>       - SHHH_API_KEY=API_KEY
> ```

The model is built into the image currently. Please try change the image line to

``` image: ghcr.io/tonym128/shhh-bot-small ```

And you can remove the model environment line... Might be an idea to support that to download a different model and build tiny into the base image... More features 😄.

**Comment by tonym128** [comment]
> Same with italian, what's weird is that I sent 2 voice messages spoken in italian:
> 
> -The first came out like this:
>  (speaking in foreign language)
>  (speaking in foreign language)
>  (speaking in foreign language)
>  
> -The second one came translated perfectly to italian 😂
>  
>  
>  I think that whisper.cpp needs the auto language detection, because it defaults to ENG
>  
>  
> ![image](https://github.com/tonym128/shhh-bot/assets/12370126/1cf6d9ff-9f2c-4538-a267-3cbc3d5fc2e2)
> EDIT: Ok It's probably not that easy

If you're able to, could you please supply a test audio sample.

I should be able to add additional settings for running whisper via the docker env. Will look into it

**Comment by cchrkk** [comment]
> > Same with italian, what's weird is that I sent 2 voice messages spoken in italian:
> > -The first came out like this:
> > (speaking in foreign language)
> > (speaking in foreign language)
> > (speaking in foreign language)
> > -The second one came translated perfectly to italian 😂
> > I think that whisper.cpp needs the auto language detection, because it defaults to ENG
> > ![image](https://private-user-images.githubusercontent.com/12370126/321266540-1cf6d9ff-9f2c-4538-a267-3cbc3d5fc2e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTkzMjcsIm5iZiI6MTcxMjc1OTAyNywicGF0aCI6Ii8xMjM3MDEyNi8zMjEyNjY1NDAtMWNmNmQ5ZmYtOWYyYy00NTM4LWEyNjctM2NiYzNkNWZjMmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE0MjM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNjgxOWIzNGQ3NjUzMjI4MDBmZGZjMDEwMThlZjVjZjRkNGNiZTk3M2E5NjQ0OWVmMDk0YjlmMTA2ZjA3NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ostgt4hdQGx0_PmSaJySslQjldbiD0_8zDkzPau79o8)
> > EDIT: Ok It's probably not that easy
> 
> If you're able to, could you please supply a test audio sample.
> 
> I should be able to add additional settings for running whisper via the docker env. Will look into it

https://file.io/wI74oMcRG5pS thank you :)

EDIT: This is bot's response to that audio :D 
![image](https://github.com/tonym128/shhh-bot/assets/12370126/06df4887-4fe3-4bbd-a35a-5faa4979aa47)

**Comment by tonym128** [comment]
Try changing your image to 
    image: ghcr.io/tonym128/shhh-bot-small

I had to convert your audio file because the first run it told me it couldn't process the .ogg file

But after I converted it to an mp3 and uploaded it, I got this response. I should have asked you for the text too 😆 

![converted_text](https://github.com/tonym128/shhh-bot/assets/1162997/a76766a6-5a86-4c87-aa9f-d036bad9b024)

**Comment by tonym128** [comment]
Ah apoligies, I misread, also getting english conversions, will look to add some more environment variables to setup how you want whisper to run.

**Comment by Coolykoen** [comment]
> The model is built into the image currently. Please try change the image line to
> 
> `image: ghcr.io/tonym128/shhh-bot-small`

So, i have now tried both -small and -medium. they certainly seem to translate now instead of interpreting it as english, thats an improvement. but it really doesnt work well. wrong words, skipped words, etc. English works great though, it even manages to understand (most of) the lyrics in songs, which is pretty cool. but yea i think dutch isnt popular enough, so it hasnt learned it that well maybe? or can i still improve something?

EDIT:
Perhaps it can just respond in dutch, skipping the translation? that would be the ideal scenario in my opinion

**Comment by tonym128** [comment]
Had a day to spend hacking! :)

image: ghcr.io/tonym128/shhh-bot

Now has the tiny model built in, but you can download a different model at startup by specifying the model in the environment
eg SHHH_WHISPER_MODEL=medium

To get persistence across runs and now have to constantly redownload it on new versions, you can mount a persistent volume for the models at /models.

You can also supply whisper.cpp options as SHHH_WHISPER_OPTIONS
-l nl - means it should assume the language is dutch
-l auto - should try to autodetect, default is english

You can search for Options on https://github.com/ggerganov/whisper.cpp to see what is available.

My current docker-compose script
```
version: '3'

services:
  shhhbot:
    container_name: shhhbot
    hostname: shhhbot
    restart: unless-stopped
    image: ghcr.io/tonym128/shhh-bot
    environment:
      - SHHH_API_KEY={API_KEY}
      - SHHH_MY_CHAT_ID={CHAT_ID}
      - SHHH_ALLOWED_CHAT_IDS={ALLOWED_CHAT_IDS}
      - SHHH_WHISPER_MODEL=medium 
      - SHHH_WHISPER_OPTIONS=-l nl
    volumes:
      - models:/models
volumes:
  models:
```

It can take a while to download the new image at startup

Here's with an example of me trying to speech some Dutch 😆 
![Dutch Example](https://github.com/tonym128/shhh-bot/assets/1162997/2b327a6a-4013-46ef-8b9e-889f4046dcd1)

**Comment by Coolykoen** [comment]
thanks! it does work really well now, amazing.

**Comment by cchrkk** [comment]
Can confirm it works wonderfully 💪🏻💪🏻 thanks a lot!
