### ISSUE TITLE
[Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by cchrkk** [tonym128/shhh-bot#7]
Hello,
I'm trying to get it to work but whenever I send a voice message to the bot it throws this message in console:

```
2024-04-08 12:57:51,511 - root - INFO - Starting bot
2024-04-08 12:57:51,678 - telegram.ext.Application - INFO - Application started
2024-04-08 12:58:20,229 - root - INFO - Started processing for cherokeee
2024-04-08 12:58:20,772 - root - ERROR - 0.5431523323059082 cherokeee : 30279797 : FAIL UNKNOWN : Failed processing message
2024-04-08 12:58:20,772 - root - ERROR - [Errno 2] No such file or directory: '/tmp/b207fd4d1e014b6fb78d3dff1d210d96.wav.txt'
```

This on telegram:
![image](https://github.com/tonym128/shhh-bot/assets/12370126/ecfda8bc-5c65-4a5e-983d-322b0e2ff860)

The compose config on portainer is the following, tried to recreate image but nothing changes

![image](https://github.com/tonym128/shhh-bot/assets/12370126/39fd1e3a-ea34-4b99-a1ec-9e341ee947a3)

**Comment by tonym128** [comment]
The wav.txt file is meant to be the speech to text output from whisper.cpp.
It seems like it failed running the convert.sh script.

Do you know what system are you running on ? X64 (Intel / Amd machine), Aarch64 (Mac Mx), ArmV6/7 (PI) ?

**Comment by cchrkk** [comment]
> The wav.txt file is meant to be the speech to text output from whisper.cpp. It seems like it failed running the convert.sh script.
> 
> Do you know what system are you running on ? X64 (Intel / Amd machine), Aarch64 (Mac Mx), ArmV6/7 (PI) ?

I'm running Alpine X64, maybe that's the problem. I should check what happens in the image creation

**Comment by tonym128** [comment]
> > The wav.txt file is meant to be the speech to text output from whisper.cpp. It seems like it failed running the convert.sh script.
> > Do you know what system are you running on ? X64 (Intel / Amd machine), Aarch64 (Mac Mx), ArmV6/7 (PI) ?
> 
> I'm running Alpine X64, maybe that's the problem. I should check what happens in the image creation

That's the image I'm running on my box, I'm making a few changes this week, will make sure I grab a new image and test with it.

**Comment by cchrkk** [comment]
Ok, let me know if you need some testing 😉

**Comment by tonym128** [comment]
This might be a 🤦 moment, can you try
ghcr.io/tonym128/shhh-bot:v1.0.0

I'm busy learning the automated docker builds and push, I don't think I'm updating the master when I push a new release, it builds it, but doesn't push it.
ghcr.io/tonym128/shhh-bot:v1.0.1 is up for testing, it allows you to not set the SHHH_MY_CHAT_ID and optionally has a SHHH_ALLOWED_CHAT_IDS to define a list of allowed users and ignore everyone else.

**Comment by cchrkk** [comment]
Tried 1.0.0, 1.0.1 and 1.0.3 but error is always the same sadly.

> it allows you to not set the SHHH_MY_CHAT_ID

I removed SHHH_MY_CHAT_ID  variable and the bot replied to me in his own chat 👌

EDIT: Same with 1.0.5

2024-04-09 08:27:08,952 - root - INFO - SHHH_MY_CHAT_ID       : None
2024-04-09 08:27:08,953 - root - INFO - SHHH_ALLOWED_CHAT_IDS : None
2024-04-09 08:27:08,980 - root - INFO - Starting bot
2024-04-09 08:27:09,149 - telegram.ext.Application - INFO - Application started
2024-04-09 08:27:31,886 - root - INFO - Started processing for None
2024-04-09 08:27:32,339 - root - ERROR - 0.4525599479675293 None : -1002132954009 : FAIL UNKNOWN : Failed processing message
2024-04-09 08:27:32,339 - root - ERROR - [Errno 2] No such file or directory: '/tmp/1aa04452512a4dd48953637264398c23.wav.txt'

**Comment by tonym128** [comment]
Please try with the latest version and let me know if you're still encountering the issue

I hava a few more images now too, tiny, base, small and medium

    image: ghcr.io/tonym128/shhh-bot-tiny
    image: ghcr.io/tonym128/shhh-bot
    image: ghcr.io/tonym128/shhh-bot-small
    image: ghcr.io/tonym128/shhh-bot-medium

**Comment by tonym128** [comment]
Here my compose script

```version: '3'

services:
  shhhbot:
    container_name: shhhbot
    hostname: shhhbot
    restart: unless-stopped
    image: ghcr.io/tonym128/shhh-bot-small
    environment:
      - SHHH_API_KEY=0000000000:xxxxxxxxxxxxx
```

That not my API key :)

Two things I can think to check are
- Check to see you have free disk space.
- Try mounting a /tmp volume into the container for the file saving

**Comment by cchrkk** [comment]
![image](https://github.com/tonym128/shhh-bot/assets/12370126/10c26a00-98b0-4f57-b546-10bf58ac926e)
Same story :D 

> Try mounting a /tmp volume into the container for the file saving

Just tried, didn't work. 
`2024-04-09 22:20:45,045 - root - ERROR - [Errno 2] No such file or directory: '/tmp/ec49a5bc3130459ca1c793f772e3ad33.wav.txt'`

>Check to see you have free disk space.

I have

**Comment by tonym128** [comment]
How are you recording the audio for Telegram ?

I use Firefox desktop or forward recordings from WhatsApp. 

I recall having issues with certain audio files in the past. I'll try add some ffmpeg logging so we can dig a bit deeper, would like to solve this issue for you.

**Comment by cchrkk** [comment]
Tried this compose:

![image](https://github.com/tonym128/shhh-bot/assets/12370126/8954c215-c886-42f4-bb68-cfcb4e39cea6)


on a debian VM and it works perfectly 🤔

**Comment by tonym128** [comment]
> Tried this compose:
> 
> ![image](https://github.com/tonym128/shhh-bot/assets/12370126/8954c215-c886-42f4-bb68-cfcb4e39cea6)
> 
> 
> on a debian VM and it works perfectly 🤔

That's great to hear you have it working. I'm working on a pr to expose error messages from ffmpeg and whisper if they occur, so we'll have more information to look at if it recurs in the future.

**Comment by cchrkk** [comment]
> > Tried this compose:
> > ![image](https://private-user-images.githubusercontent.com/12370126/321263709-8954c215-c886-42f4-bb68-cfcb4e39cea6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTk3MzQsIm5iZiI6MTcxMjc1OTQzNCwicGF0aCI6Ii8xMjM3MDEyNi8zMjEyNjM3MDktODk1NGMyMTUtYzg4Ni00MmY0LWJiNjgtY2ZjYjRlMzljZWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE0MzAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNzU1ZjczMzI3OTNhNDMzYjk3NGU4NGE5MjlmOGJmY2NkZDE3MTg3ODYxYmI1NDBhYzk4ZWY0MTc4NmVmMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DQv_uyehJBRtIkbhi54x373E8kkepW2fTdfNpBQwx6g)
> > on a debian VM and it works perfectly 🤔
> 
> That's great to hear you have it working. I'm working on a pr to expose error messages from ffmpeg and whisper if they occur, so we'll have more information to look at if it recurs in the future.

Yay perfect, I've tried to debug the convert script but I'm too noob to understand how. That would help!

**Comment by cchrkk** [comment]
Working perfectly on debian, but I get this error in alpine:

```
Done! Model 'medium' saved in '/models/ggml-medium.bin'
You can now use it like this:
  $ ./main -m /models/ggml-medium.bin -f samples/jfk.wav
Link model to whisper one
Complete
2024-04-12 13:22:56,830 - root - INFO - Starting bot
2024-04-12 13:22:56,998 - telegram.ext.Application - INFO - Application started
2024-04-12 13:31:35,089 - root - INFO - Started processing for cherokeee
2024-04-12 13:31:35,458 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/src/shhh.py", line 145, in handle_message
    result = open(filename+".wav.txt", "r")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/aeb530ddaf1a4142a5640b30f04481bd.wav.txt'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 1264, in process_update
    await coroutine
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
  File "/usr/local/src/shhh.py", line 167, in handle_message
    with open("/tmp/convert.log", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/convert.log'
```
same compose i'm using on debian:
![image](https://github.com/tonym128/shhh-bot/assets/12370126/5382d442-9cc1-42f6-9331-edf63eeaae3c)

**Comment by frnprt** [comment]
Hi! First thing first thanks for your work, this is an awesome tool if one has some metal to spare and doesn't want to give 23 buck per year to TG.

I hate to necro a closed topic, but I have encountered this error too and it I think it may be related to this issue:
https://github.com/ggerganov/whisper.cpp/issues/83

It seems that the CPU lacks specific instructions invoked by Whisper (which I guess may happen if the CPU is old enough - in my case its almost 12 years old). Probably it's a non-AVX CPU.

A possible solution (albeit to test yet) to enable retrocompatibility could be to allow local compilation of the model (via .env variables) and to run Cmake with the `-DWHISPER_NO_SIMD=ON` parameter.
